# MODE: http

version: '3'

services:

  espocrm-db:
    image: mariadb:latest
    container_name: espocrm-db
    command: --max-allowed-packet=64MB
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: %%DB_ROOT_PASSWORD%%
      MARIADB_DATABASE: espocrm
      MARIADB_USER: espocrm
      MARIADB_PASSWORD: %%DB_PASSWORD%%
    volumes:
      - ./data/mariadb/data:/var/lib/mysql
    networks:
      - internal

  espocrm-nginx:
    image: nginx:latest
    container_name: espocrm-nginx
    environment:
      NGINX_HOST: %%DOMAIN_NAME%%
    volumes:
      - ./data/nginx/conf.d/:/etc/nginx/templates
      - ./data/espocrm:/var/www/html
      - ./data/nginx/espocrm.conf:/etc/nginx/espocrm.conf
      - ./data/nginx/logs:/var/log/nginx
    restart: always
    depends_on:
      - espocrm
      - espocrm-websocket
    ports:
      - "80:80"
    networks:
      - external
      - internal

  espocrm:
    image: espocrm/espocrm:fpm
    container_name: espocrm
    environment:
      ESPOCRM_DATABASE_HOST: espocrm-db
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: %%DB_PASSWORD%%
      ESPOCRM_ADMIN_USERNAME: %%ADMIN_USERNAME%%
      ESPOCRM_ADMIN_PASSWORD: %%ADMIN_PASSWORD%%
      ESPOCRM_CONFIG_SITE_URL: "%%ESPOCRM_SITE_URL%%"
    restart: always
    depends_on:
      - espocrm-db
    volumes:
     - ./data/espocrm:/var/www/html
    networks:
      - external
      - internal

  espocrm-daemon:
    image: espocrm/espocrm:fpm
    container_name: espocrm-daemon
    volumes:
     - ./data/espocrm:/var/www/html
    restart: always
    depends_on:
      - espocrm
    entrypoint: docker-daemon.sh
    networks:
      - external
      - internal

  espocrm-websocket:
    container_name: espocrm-websocket
    image: espocrm/espocrm:fpm
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
    volumes:
     - ./data/espocrm:/var/www/html
    restart: always
    depends_on:
      - espocrm
    entrypoint: docker-websocket.sh
    ports:
      - "8080:8080"
    networks:
      - external
      - internal

networks:
  external:
    driver: bridge
  internal:
    external: false
